
DROP TABLE WORD IF EXISTS;
CREATE TABLE WORD (
ENGLISH           VARCHAR(128) NOT NULL,
CHINESE           VARCHAR(256),
PRACTISE_COUNT    INTEGER NOT NULL DEFAULT 0,
REMEMBER_COUNT    INTEGER NOT NULL DEFAULT 0,

UPDATE_DATE       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);